### ISSUE TITLE
Домашняя работа №4

### ISSUE THREAD

**Issue by UmanskiyDan** [MIEE-ACS/domashnee-zadanie-no4-UmanskiyDan#1]
Домашняя работа №4 сделана, в консольном приложении

**Comment by d-makarenko** [comment]
1 задание:

```c#
                    double[] Dim1Array = new double[n];
                    double SumNeg = 0;
                    double MaxSc = Dim1Array[0];
                    double MinSc = Dim1Array[0];
```
Тут присваивается значение переменным MaxSc & MinSc до того как массив заполнен, а по умолчанию там нули. Соответственно в некоторых ситуациях неправильно находится индекс минимального элемента и последующие расчеты.

**Comment by d-makarenko** [comment]
2 задание - хорошо.

**Comment by UmanskiyDan** [comment]
Проблема решена разделением цикла на 2 других

**Comment by d-makarenko** [comment]
Да, хорошо
